%%  step10_combination_ML_inference

%  Runs ML classifier inference for anthracycline+OLM drug combinations
%  using the 400 trained models. Normalizes scores across 9 treatment
%  groups (DMSO, 4 drugs, 4 drug+OLM combos). Generates beeswarm+boxplot
%  figures with permutation-test p-values.
%
%  Requirements:
%    - MATLAB
%    - Statistics and Machine Learning Toolbox
%                                   (predict, signrank, signtest,
%                                    swarmchart, boxchart, bootci)
%    - GPU required                 (gpuArray for 1M-permutation bootstrap)
%
%  Inputs:
%    - out/RxnStats_DOX_vs_DOXOLM.mat  — Per-combo reaction stats
%    - out/RxnStats_IDA_vs_IDAOLM.mat    (generated by running step09
%    - out/RxnStats_DAU_vs_DAUOLM.mat     with each combo pair)
%    - out/RxnStats_EPI_vs_EPIOLM.mat
%    - out/iCardio_optimized.mat        — ModelOpt
%    - out/DICT_L0X/c1_<date>/Rxn_models_<a>.mat
%                                       — 400 trained Rxn classifiers
%
%  Outputs:
%    - out/driver10_rawScores_ALLCOMBOS.mat     — Raw ML scores per group
%    - out/driver10_normScores_ALLCOMBOS.mat    — Normalized scores
%    - figures/Fig10_AllCombos_Beeswarm_Boxplot.png/.fig
%    - figures/Fig10_Delta_OLM_Effect.png/.fig

clear; clc; close all;

%% ========================== CONFIGURATION ==========================

% Toggle phases
RUN_INFERENCE     = true;   % heavy; do once
RUN_NORMALIZE_FIG = true;   % cheap; can re-run any time

% Experiment configuration for loading ML models
expName           = "DICT_L0X";
currentDateString = "10_6_30hr";
iRange            = 1:100;
cMax              = 4;

% Drug combinations (must match driver9)
DrugCombList = { ...
    {"DOX", "OLM"}, ...
    {"IDA", "OLM"}, ...
    {"DAU", "OLM"}, ...
    {"EPI", "OLM"}  ...
    };
numCombos = numel(DrugCombList);

% File naming used by driver9
comboPairStrs = cell(numCombos, 1);
for c = 1:numCombos
    comboPairStrs{c} = sprintf('%s_vs_%s', ...
        char(DrugCombList{c}{1}), ...
        [char(DrugCombList{c}{1}) char(DrugCombList{c}{2})]);
end

% Stats type label (primarily bookkeeping)
STAT_TYPE = 'MedMed';

% Save options
SAVE_FIG = true;
SAVE_MAT = true;

if ~exist('out','dir'),     mkdir('out');     end
if ~exist('figures','dir'), mkdir('figures'); end

fprintf('\n========================================\n');
fprintf('DRIVER 10: Inference + Normalization\n');
fprintf('========================================\n\n');

%% ======================= INFERENCE PHASE ===========================
% This phase:
%   - loads GEM + ML models
%   - loads driver9 per-combo RxnStats
%   - builds features per combo (DMSO, Drug, Drug+OLM)
%   - runs ML inference for all models
%   - saves raw scores but does NOT normalize or plot

if RUN_INFERENCE

    % Load model
    fprintf('Loading optimized model...\n');
    load(fullfile('out','iCardio_optimized.mat'), 'ModelOpt');
    Model = ModelOpt;
    clear ModelOpt;
    Model.N   = null(full(Model.S));
    Model.NNp = Model.N * Model.N';
    fprintf('Model loaded: %d reactions, %d metabolites\n', numel(Model.rxns), numel(Model.mets));

    predictorNames = "x" + string(num2str((1:numel(Model.rxns))'));

    % Load all ML models
    fprintf('\nLoading trained ML models...\n');
    basePath   = fullfile("out", expName, "c1_" + currentDateString);
    numModels  = 400;
    allModels  = cell(numModels, 1);
    modelCount = 1;

    for idx = 1:numel(iRange)
        a = iRange(idx);
        modelFile = fullfile(basePath, sprintf('Rxn_models_%d.mat', a));
        if ~exist(modelFile, 'file')
            continue;
        end
        load(modelFile, 'tRxn_models');
        for c = 1:cMax
            if modelCount <= numModels
                allModels{modelCount} = tRxn_models{1,c};
                modelCount = modelCount + 1;
            end
        end
    end

    allModels = allModels(~cellfun(@isempty, allModels));
    numModels = numel(allModels);
    fprintf('Loaded %d ML models\n', numModels);
end
%%
if RUN_INFERENCE
    % Inference output container
    % We want global 9 groups:
    %   1: DMSO (shared baseline)
    %   2: DOX
    %   3: DOX+OLM
    %   4: IDA
    %   5: IDA+OLM
    %   6: DAU
    %   7: DAU+OLM
    %   8: EPI
    %   9: EPI+OLM
    %
    % For each model, we will have a 9x1 vector of raw scores.

    rawScoresAll = struct();
    rawScoresAll.numModels    = numModels;
    rawScoresAll.comboPairs   = comboPairStrs;
    rawScoresAll.DrugCombList = DrugCombList;
    rawScoresAll.STAT_TYPE    = STAT_TYPE;

    % Preallocate per-group arrays
    rawScoresAll.DMSO     = nan(numModels, 1);
    rawScoresAll.DOX      = nan(numModels, 1);
    rawScoresAll.DOX_OLM  = nan(numModels, 1);
    rawScoresAll.IDA      = nan(numModels, 1);
    rawScoresAll.IDA_OLM  = nan(numModels, 1);
    rawScoresAll.DAU      = nan(numModels, 1);
    rawScoresAll.DAU_OLM  = nan(numModels, 1);
    rawScoresAll.EPI      = nan(numModels, 1);
    rawScoresAll.EPI_OLM  = nan(numModels, 1);

    % We will fill per-combo then map into these fields

    % One shared DMSO feature vector (all zeros) with same length as first combo
    baseCtrlFeatures = [];

    % Loop over combos and run inference
    for comboIdx = 1:numCombos

        comboPair = comboPairStrs{comboIdx};
        drug1     = char(DrugCombList{comboIdx}{1});
        drug2     = char(DrugCombList{comboIdx}{2});

        fprintf('\n=== COMBO %d/%d: %s vs %s ===\n', comboIdx, numCombos, drug1, drug2);

        statsFile = fullfile('out', sprintf('RxnStats_%s.mat', comboPair));
        if ~exist(statsFile, 'file')
            fprintf('  WARNING: %s not found. Skipping combo.\n', statsFile);
            continue;
        end

        fprintf('  Loading RxnStats: %s\n', statsFile);
        load(statsFile, 'comboRxnStats');

        % Extract MedMed reaction stats
        RxnStats_Drug = comboRxnStats.RxnMedMed_Drug;
        RxnStats_Conv = comboRxnStats.RxnMedMed_Conv;

        % Drug features
        if height(RxnStats_Drug) > 0 && width(RxnStats_Drug) > 0
            tmp = RxnStats_Drug.MedianDiff;
            %tmp(ismissing(tmp)) = 0;
            drugFeatures = table2array(tmp(:,1));
        else
            drugFeatures = zeros(1,1);
        end

        % Combo features
        if height(RxnStats_Conv) > 0 && width(RxnStats_Conv) > 0
            tmp = RxnStats_Conv.MedianDiff;
            %tmp(ismissing(tmp)) = 0;
            convFeatures = table2array(tmp(:,1));
        else
            convFeatures = zeros(1,1);
        end

        % Set shared DMSO baseline length the first time
        if isempty(baseCtrlFeatures)
            baseCtrlFeatures = zeros(size(drugFeatures));
        else
            % ensure lengths match; pad/truncate if needed
            L = min(numel(baseCtrlFeatures), numel(drugFeatures));
            baseCtrlFeatures = baseCtrlFeatures(1:L);
            drugFeatures     = drugFeatures(1:L);
            convFeatures     = convFeatures(1:L);
        end

        % Build feature matrices
        numReactions = numel(predictorNames);
        numFeatures  = numel(baseCtrlFeatures);

        X_ctrl = zeros(1, numReactions);
        X_drug = zeros(1, numReactions);
        X_conv = zeros(1, numReactions);

        maxIdx           = min(numFeatures, numReactions);
        X_ctrl(1,1:maxIdx) = baseCtrlFeatures(1:maxIdx)';
        X_drug(1,1:maxIdx) = drugFeatures(1:maxIdx)';
        X_conv(1,1:maxIdx) = convFeatures(1:maxIdx)';

        fprintf('  Feature length used: %d reactions\n', maxIdx);
        fprintf('  Running ML inference across %d models...\n', numModels);

        tox_ctrl = nan(numModels, 1);
        tox_drug = nan(numModels, 1);
        tox_conv = nan(numModels, 1);

        for m = 1:numModels
            try
                mdl = allModels{m};
                mdl.ScoreTransform = "doublelogit";
                [~, scoreCtrl] = predict(mdl, X_ctrl);
                [~, scoreDrug] = predict(mdl, X_drug);
                [~, scoreConv] = predict(mdl, X_conv);
                tox_ctrl(m)    = scoreCtrl(1,2);
                tox_drug(m)    = scoreDrug(1,2);
                tox_conv(m)    = scoreConv(1,2);
            catch
                % leave NaN
                disp("inference did not run" + comboIdx + m)
            end
        end

        % Map into global fields
        % All combos share the same DMSO baseline, so overwrite is fine
        rawScoresAll.DMSO = tox_ctrl;

        switch drug1
            case 'DOX'
                rawScoresAll.DOX     = tox_drug;
                rawScoresAll.DOX_OLM = tox_conv;
            case 'IDA'
                rawScoresAll.IDA     = tox_drug;
                rawScoresAll.IDA_OLM = tox_conv;
            case 'DAU'
                rawScoresAll.DAU     = tox_drug;
                rawScoresAll.DAU_OLM = tox_conv;
            case 'EPI'
                rawScoresAll.EPI     = tox_drug;
                rawScoresAll.EPI_OLM = tox_conv;
        end

        fprintf('  Combo %s done.\n', comboPair);
    end

    % Save raw scores once
    if SAVE_MAT
        save(fullfile('out','driver10_rawScores_ALLCOMBOS.mat'), ...
            'rawScoresAll','-v7.3');
        fprintf('\nSaved raw scores to out/driver10_rawScores_ALLCOMBOS.mat\n');
    end
end % RUN_INFERENCE

%% ================= NORMALIZATION + FIGURE PHASE ====================
% This phase:
%   - loads driver10_rawScores_ALLCOMBOS.mat
%   - performs normalization across all 9 groups
%   - creates one beeswarm+boxplot figure
%   - saves normalized matrix

if RUN_NORMALIZE_FIG

    fprintf('\n=== NORMALIZATION + FIGURE PHASE ===\n');

    % Load raw scores (if not in workspace)
    if ~exist('rawScoresAll','var')
        load(fullfile('out','driver10_rawScores_ALLCOMBOS.mat'), 'rawScoresAll');
    end

    numModels = rawScoresAll.numModels;

    % Build 9-column matrix: rows=models, cols=treatments
    % Order: DMSO, DOX, DOX+OLM, IDA, IDA+OLM, DAU, DAU+OLM, EPI, EPI+OLM
    allRaw = [ ...
        rawScoresAll.DMSO, ...
        rawScoresAll.DOX, ...
        rawScoresAll.DOX_OLM, ...
        rawScoresAll.IDA, ...
        rawScoresAll.IDA_OLM, ...
        rawScoresAll.DAU, ...
        rawScoresAll.DAU_OLM, ...
        rawScoresAll.EPI, ...
        rawScoresAll.EPI_OLM ...
        ];

    treatmentLabels = { ...
        'DMSO', ...
        'DOX',      'DOX+OLM', ...
        'IDA',      'IDA+OLM', ...
        'DAU',      'DAU+OLM', ...
        'EPI',      'EPI+OLM' ...
        };

    fprintf('  Normalizing scores per model (plateau-style)...\n');

    % Handle inf
    tmp    = allRaw;
    finite = tmp(~isinf(tmp) & ~isnan(tmp));
    maxVal = max(finite, [], 'all');
    minVal = min(finite, [], 'all');
    tmp(isinf(tmp) & tmp > 0) = maxVal * 2;
    tmp(isinf(tmp) & tmp < 0) = minVal * 2;

    allRaw = tmp;

    baseline = allRaw(:,1);                                   % DMSO
    diffs    = allRaw - baseline;                             % subtract row-wise
    absDiffs = abs(diffs(:,2:end));                           % exclude DMSO itself
    denom    = max(absDiffs, [], 2);                          % per-row max deviation
    denom(denom == 0 | isnan(denom)) = 1;                     % safe

    normAll = diffs ./ denom;                                 % broadcast row-wise

    % normAll(:,1) should be exactly 0 (baseline)
    % Columns: same order as treatmentLabels

    if SAVE_MAT
        normResults = struct();
        normResults.normAll         = normAll;
        normResults.allRaw          = allRaw;
        normResults.treatmentLabels = treatmentLabels;
        normResults.numModels       = numModels;
        normResults.STAT_TYPE       = STAT_TYPE;

        save(fullfile('out','driver10_normScores_ALLCOMBOS.mat'), ...
            'normResults','-v7.3');
        fprintf('  Saved normalized scores to out/driver10_normScores_ALLCOMBOS.mat\n');
    end

    % Single Beeswarm + Boxplot Figure (9 groups)
    fprintf(' Creating beeswarm + boxplot figure (9 groups)...\n');

    fig = figure('Units','centimeters','Position',[2,2,28,12],'Color','w');
    hold on;

    numGroups = numel(treatmentLabels);

    % Colors: gray for DMSO, then pairs per drug
    colors = [ ...
        0.6 0.6 0.6; ... % DMSO
        0.8 0.2 0.2; ... % DOX
        0.9 0.4 0.4; ... % DOX+OLM
        0.2 0.5 0.8; ... % IDA
        0.4 0.6 0.9; ... % IDA+OLM
        0.2 0.7 0.2; ... % DAU
        0.4 0.8 0.4; ... % DAU+OLM
        0.7 0.3 0.8; ... % EPI
        0.8 0.5 0.9 ... % EPI+OLM
        ];

    % Prepare data for swarmchart: need column vectors for x and y
    xData = [];
    yData = [];
    colorData = [];
    for g = 1:numGroups
        groupData = normAll(:, g);
        xData = [xData; repmat(g, numModels, 1)];
        yData = [yData; groupData];
        colorData = [colorData; repmat(colors(g,:), numModels, 1)];
    end

    % Swarmchart
    swarmchart(xData(yData ~= 1), yData(yData ~= 1), 20, colorData((yData ~= 1),:), 'filled', 'MarkerFaceAlpha', 0.5, "XJitter", "density", "XJitterWidth",1);

    % Boxplot overlay
    boxplot(normAll, 'Labels', treatmentLabels, 'Colors', 'k', ...
        'Widths', 0.75, 'Symbol', '', 'BoxStyle', 'outline', 'Notch','on');

    % Add p-values for drug vs drug+OLM comparisons (after boxplot)
    drugPairs = [2,3; 4,5; 6,7; 8,9]; % DOX, IDA, DAU, EPI pairs
    yMax = max(normAll(:)) + 0.01; % Position above data

    for i = 1:size(drugPairs,1)
        g1 = drugPairs(i,1);
        g2 = drugPairs(i,2);
        [p, ~, ~, ~, ~] = permutation_test_with_bootstrap(normAll(:,g1), normAll(:,g2));
        p = min(p.*4, 1);

        % Format p-value
        if p < 0.001
            pText = 'p<0.001';
        elseif p > 0.999
            pText = 'p=1';
        else
            pText = sprintf('p=%.3f', p);
        end

        % Draw line and add text
        xMid = mean([g1, g2]);
        plot([g1, g2], [yMax, yMax], 'k-', 'LineWidth', 1);
        text(xMid, yMax+0.01, pText, 'HorizontalAlignment', 'center', ...
            'FontSize', 9, 'FontWeight', 'bold');
    end


    % Labels and formatting
    ylabel('Normalized Toxicity Score (DMSO baseline = 0)', 'FontSize', 12, 'FontWeight', 'bold');
    xlabel('Treatment', 'FontSize', 12, 'FontWeight', 'bold');
    title('ML-Predicted Normalized Toxicity Across Anthracycline+OLM Combos', ...
        'FontSize', 13, 'FontWeight', 'bold');
    xtickangle(45);
    grid on; grid minor;
    set(gca, 'FontSize', 10);
    xlim([1.5, numGroups+0.5]);
    ylim([0.798 1.025])

    if SAVE_FIG
        fpath_png = fullfile('figures', 'Fig10_AllCombos_Beeswarm_Boxplot.png');
        fpath_fig = fullfile('figures', 'Fig10_AllCombos_Beeswarm_Boxplot.fig');
        saveas(fig, fpath_png);
        savefig(fig, fpath_fig);
        fprintf('  Saved figure:\n    %s\n    %s\n', fpath_png, fpath_fig);
    end

    fprintf('=== NORMALIZATION + FIGURE PHASE DONE ===\n\n');

end % RUN_NORMALIZE_FIG

%%


fprintf('\n=== PAIRED DELTA ANALYSIS ===\n');

% Calculate delta scores (normalized +OLM minus normalized -OLM)
% Columns from normAll: DOX=2, DOX+OLM=3, IDA=4, IDA+OLM=5, DAU=6, DAU+OLM=7, EPI=8, EPI+OLM=9
deltaDOX = normAll(:,3) - normAll(:,2);  % DOX+OLM - DOX
deltaIDA = normAll(:,5) - normAll(:,4);  % IDA+OLM - IDA
deltaDAU = normAll(:,7) - normAll(:,6);  % DAU+OLM - DAU
deltaEPI = normAll(:,9) - normAll(:,8);  % EPI+OLM - EPI

% Combine into matrix for plotting
deltaData = [deltaDOX, deltaIDA, deltaDAU, deltaEPI];
deltaLabels = {'DOX', 'IDA', 'DAU', 'EPI'};

% Create figure
figDelta = figure('Units','centimeters','Position',[2,2,16,12],'Color','w');
hold on;

% Colors for each drug
deltaColors = [ ...
    0.8 0.2 0.2; ... % DOX
    0.2 0.5 0.8; ... % IDA
    0.2 0.7 0.2; ... % DAU
    0.7 0.3 0.8  ... % EPI
    ];

% Prepare data for swarmchart
xDataDelta = [];
yDataDelta = [];
colorDataDelta = [];

for g = 1:4
    groupDelta = deltaData(:, g);
    xDataDelta = [xDataDelta; repmat(g, numModels, 1)];
    yDataDelta = [yDataDelta; groupDelta];
    colorDataDelta = [colorDataDelta; repmat(deltaColors(g,:), numModels, 1)];
end

% Swarmchart
swarmchart(xDataDelta(yDataDelta ~= 0), yDataDelta(yDataDelta ~= 0), 25, colorDataDelta(yDataDelta ~= 0,:), 'filled', ...
    'MarkerFaceAlpha', 0.6, 'XJitter', 'density', 'XJitterWidth', 0.8);

% Boxplot overlay
boxplot(deltaData, 'Labels', deltaLabels, 'Colors', 'k', ...
    'Widths', 0.6, 'Symbol', '', 'BoxStyle', 'outline', 'Notch', 'on');

% Perform sign test for each drug and add p-values
yMax = max(deltaData(:));
yMin = min(deltaData(:));
yRange = yMax - yMin;
pTextY = yMax + 0.05 * yRange;

for g = 1:4
    % Sign test: H0: median(delta) = 0
    [p, ~, stats] = signtest(deltaData(:, g));
    p = min(p.*4, 1);
    % Format p-value
    if p < 0.001
        pText = 'p<0.001';
    elseif p > 0.999
        pText = 'p=1';
    else
        pText = sprintf('p=%.3f', p);
    end

    % Add text above each group
    text(g, 0.009, pText, 'HorizontalAlignment', 'center', ...
        'FontSize', 10, 'FontWeight', 'bold');
end

% Add reference line at y=0
yline(0, 'k--', 'LineWidth', 1.5, 'Alpha', 0.7);

% Labels and formatting
ylabel('\Delta Toxicity Score (+OLM minus -OLM)', 'FontSize', 12, 'FontWeight', 'bold');
xlabel('Anthracycline', 'FontSize', 12, 'FontWeight', 'bold');
title('Olmesartan Effect on ML-Predicted Cardiotoxicity', ...
    'FontSize', 13, 'FontWeight', 'bold');
grid on; grid minor;
set(gca, 'FontSize', 11);
xlim([0.5, 4.5]);
ylim([-0.02 0.01 ])

if SAVE_FIG
    fpath_png = fullfile('figures', 'Fig10_Delta_OLM_Effect.png');
    fpath_fig = fullfile('figures', 'Fig10_Delta_OLM_Effect.fig');
    saveas(figDelta, fpath_png);
    savefig(figDelta, fpath_fig);
    fprintf(' Saved delta figure:\n   %s\n   %s\n', fpath_png, fpath_fig);
end

fprintf('=== PAIRED DELTA ANALYSIS DONE ===\n\n');

%%
function [p_value, perm_diff, obs_diff, ci_perm, ci_boot] = permutation_test_with_bootstrap(group1, group2)
% Permutation test with bootstrap confidence intervals - GPU accelerated
n_permutations = 1000000;
n = length(group1);
differences = group1 - group2;
obs_diff = mean(differences);

% GPU-accelerated permutation test
differences_gpu = gpuArray(differences);  % Move differences to GPU

% Generate all sign flips on GPU at once
signs_gpu = 2 * (rand(n, n_permutations, 'gpuArray') > 0.5) - 1;

% Element-wise multiplication and mean (all on GPU)
perm_differences_gpu = differences_gpu .* signs_gpu;
perm_diffs_gpu = mean(perm_differences_gpu, 1);

% Gather results back to CPU for final calculations
perm_diffs = gather(perm_diffs_gpu)';
perm_diff = mean(perm_diffs);
p_value = (sum(abs(perm_diffs) >= abs(obs_diff)) + 1) / (n_permutations + 1);

% Bootstrap CI (BCa method) - runs on CPU
try
    ci_boot = bootci(10000, {@mean, differences}, 'Type', 'bca', 'Alpha', 0.05/4);
catch
    ci_boot = bootci(10000, {@mean, differences}, 'Type', 'percentile', 'Alpha', 0.05/4);
end
ci_perm = [];
end
